import json
from datetime import datetime
from pathlib import Path


# ==================================================
# CONFIGURATION
# ==================================================

INCIDENT_FILE = Path(
    "outputs/incidents.json"
)


# ==================================================
# LOAD INCIDENTS
# ==================================================

def load_incidents():
    """
    Load existing incidents from the JSON file.
    """

    if not INCIDENT_FILE.exists():
        return []

    try:
        with open(
            INCIDENT_FILE,
            "r",
            encoding="utf-8"
        ) as file:

            data = json.load(file)

        if isinstance(data, list):
            return data

        return []

    except (
        json.JSONDecodeError,
        FileNotFoundError,
        OSError
    ):
        return []


# ==================================================
# SAVE INCIDENT
# ==================================================

def save_incident(
    event_type,
    location,
    severity,
    badge_detected=False,
    badge_id=None,
    snapshot_path=None,
    event_time=None,
    camera_id="CAM-01"
):
    """
    Save an incident generated by any CareFlow
    detection module.

    Supported events:
    1. Restricted Zone Entry
    2. Exit Obstruction
    3. Future safety events
    """

    incidents = load_incidents()


    # ==================================================
    # EVENT TIME
    # ==================================================

    if event_time is None:
        event_time = datetime.now()


    # ==================================================
    # VALID EVENT TYPES
    # ==================================================

    valid_event_types = [
        "restricted_zone_entry",
        "exit_obstruction"
    ]

    if event_type not in valid_event_types:

        raise ValueError(
            f"Unsupported event type: {event_type}"
        )


    # ==================================================
    # GENERATE INCIDENT ID
    # ==================================================

    incident_number = len(incidents) + 1

    incident_id = (
        f"INC-{incident_number:04d}"
    )


    # ==================================================
    # CREATE INCIDENT
    # ==================================================

    incident = {

        "incident_id":
            incident_id,

        "camera_id":
            camera_id,

        "event_type":
            event_type,

        "location":
            location,

        "severity":
            severity,

        "badge_detected":
            badge_detected,

        "badge_id":
            badge_id,

        "snapshot":
            str(snapshot_path)
            if snapshot_path
            else None,

        "timestamp":
            event_time.strftime(
                "%Y-%m-%d %H:%M:%S"
            ),

        "status":
            "OPEN"
    }


    # ==================================================
    # ADD INCIDENT
    # ==================================================

    incidents.append(incident)


    # ==================================================
    # CREATE OUTPUT DIRECTORY
    # ==================================================

    INCIDENT_FILE.parent.mkdir(
        parents=True,
        exist_ok=True
    )


    # ==================================================
    # WRITE INCIDENTS
    # ==================================================

    with open(
        INCIDENT_FILE,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            incidents,
            file,
            indent=4
        )


    print(
        f"📝 Incident saved: {incident_id}"
    )

    return incident